server:
  port: 4444
  
  
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true 
    
    
spring:
  cloud:
    gateway:
      routes:
        - id: FOTBALIST-SERVICE
          uri:
            lb://FOTBALIST-SERVICE
          #  http://localhost:2222
          predicates:
            - Path=/fotbalist/**

        - id: ECHIPA-SERVICE
          uri:
            lb://ECHIPA-SERVICE
          predicates:
            - Path=/echipa/**      
